import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: '快速开始',
      collapsed: true,
      items: [
        'getting-started/quickstart',
        'getting-started/installation',
        'getting-started/nix-setup',
        'getting-started/updating',
        'getting-started/learning-path',
      ],
    },
    {
      type: 'category',
      label: '使用指南',
      collapsed: true,
      items: [
        'user-guide/cli',
        'user-guide/configuration',
        'user-guide/sessions',
        'user-guide/profiles',
        'user-guide/git-worktrees',
        'user-guide/docker',
        'user-guide/security',
        'user-guide/checkpoints-and-rollback',
      ],
    },
    {
      type: 'category',
      label: '功能特性',
      collapsed: true,
      items: [
        'user-guide/features/overview',
        {
          type: 'category',
          label: '核心功能',
          items: [
            'user-guide/features/tools',
            'user-guide/features/skills',
            'user-guide/features/memory',
            'user-guide/features/memory-providers',
            'user-guide/features/context-files',
            'user-guide/features/context-references',
            'user-guide/features/personality',
            'user-guide/features/skins',
            'user-guide/features/plugins',
          ],
        },
        {
          type: 'category',
          label: '自动化',
          items: [
            'user-guide/features/cron',
            'user-guide/features/delegation',
            'user-guide/features/code-execution',
            'user-guide/features/hooks',
            'user-guide/features/batch-processing',
          ],
        },
        {
          type: 'category',
          label: '媒体与网页',
          items: [
            'user-guide/features/voice-mode',
            'user-guide/features/browser',
            'user-guide/features/vision',
            'user-guide/features/image-generation',
            'user-guide/features/tts',
          ],
        },
        {
          type: 'category',
          label: '高级功能',
          items: [
            'user-guide/features/rl-training',
          ],
        },
        {
          type: 'category',
          label: '技能',
          items: [
            'user-guide/skills/godmode',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '消息平台',
      collapsed: true,
      items: [
        'user-guide/messaging/index',
        'user-guide/messaging/telegram',
        'user-guide/messaging/discord',
        'user-guide/messaging/slack',
        'user-guide/messaging/whatsapp',
        'user-guide/messaging/signal',
        'user-guide/messaging/email',
        'user-guide/messaging/sms',
        'user-guide/messaging/homeassistant',
        'user-guide/messaging/mattermost',
        'user-guide/messaging/matrix',
        'user-guide/messaging/dingtalk',
        'user-guide/messaging/feishu',
        'user-guide/messaging/wecom',
        'user-guide/messaging/open-webui',
        'user-guide/messaging/webhooks',
      ],
    },
    {
      type: 'category',
      label: '集成',
      collapsed: true,
      items: [
        'integrations/index',
        'integrations/providers',
        'user-guide/features/mcp',
        'user-guide/features/acp',
        'user-guide/features/api-server',
        'user-guide/features/honcho',
        'user-guide/features/provider-routing',
        'user-guide/features/fallback-providers',
        'user-guide/features/credential-pools',
      ],
    },
    {
      type: 'category',
      label: '教程与指南',
      collapsed: true,
      items: [
        'guides/tips',
        'guides/local-llm-on-mac',
        'guides/daily-briefing-bot',
        'guides/team-telegram-assistant',
        'guides/python-library',
        'guides/use-mcp-with-hermes',
        'guides/use-soul-with-hermes',
        'guides/use-voice-mode-with-hermes',
        'guides/build-a-hermes-plugin',
        'guides/automate-with-cron',
        'guides/work-with-skills',
        'guides/delegation-patterns',
        'guides/migrate-from-openclaw',
      ],
    },
    {
      type: 'category',
      label: '开发者指南',
      collapsed: true,
      items: [
        'developer-guide/contributing',
        {
          type: 'category',
          label: '架构',
          items: [
            'developer-guide/architecture',
            'developer-guide/agent-loop',
            'developer-guide/prompt-assembly',
            'developer-guide/context-compression-and-caching',
            'developer-guide/gateway-internals',
            'developer-guide/session-storage',
            'developer-guide/provider-runtime',
          ],
        },
        {
          type: 'category',
          label: '扩展开发',
          items: [
            'developer-guide/adding-tools',
            'developer-guide/adding-providers',
            'developer-guide/memory-provider-plugin',
            'developer-guide/creating-skills',
            'developer-guide/extending-the-cli',
          ],
        },
        {
          type: 'category',
          label: '内部实现',
          items: [
            'developer-guide/tools-runtime',
            'developer-guide/acp-internals',
            'developer-guide/cron-internals',
            'developer-guide/environments',
            'developer-guide/trajectory-format',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '参考手册',
      items: [
        'reference/cli-commands',
        'reference/slash-commands',
        'reference/profile-commands',
        'reference/environment-variables',
        'reference/tools-reference',
        'reference/toolsets-reference',
        'reference/mcp-config-reference',
        'reference/skills-catalog',
        'reference/optional-skills-catalog',
        'reference/faq',
      ],
    },
  ],
};

export default sidebars;
